Basic Python

In [1]:
s = "Hi there Sam!"
s_list = s.split(" ")
for i in s_list:
  print(i)

Hi
there
Sam!


Use .format() to print the following string.

In [3]:
planet = "Earth"
diameter = 12742
result = "The diameter of {Name} is {Value} kilometers". format(Name = planet, Value = diameter)
print(result)

The diameter of Earth is 12742 kilometers


In this nest dictionary grab the word "hello"

In [4]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello


Numpy

In [6]:
import numpy as np
arr1 = np.zeros(10)
print(arr1)
arr2 = np.ones(10)*5
print(arr2)
arr3 = np.arange(20,35,2)
print(arr3)
arr4 = np.arange(0,9).reshape(3,3)
print(arr4)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
arr5 = np.concatenate((a, b))
print(arr5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[20 22 24 26 28 30 32 34]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1 2 3 4 5 6]


Pandas

In [7]:
import pandas as pd
res = pd.DataFrame(np.random.randint(0,100,size=(3, 2)), columns=list('AB'))
print(res)

    A   B
0  95  89
1  56  37
2  20  44


In [8]:
import pandas as pd 
date = pd.date_range(start ='1-1-2023', end ='5-10-2023', freq ='10D')
  
for val in date:
    print(val)

2023-01-01 00:00:00
2023-01-11 00:00:00
2023-01-21 00:00:00
2023-01-31 00:00:00
2023-02-10 00:00:00
2023-02-20 00:00:00
2023-03-02 00:00:00
2023-03-12 00:00:00
2023-03-22 00:00:00
2023-04-01 00:00:00
2023-04-11 00:00:00
2023-04-21 00:00:00
2023-05-01 00:00:00


In [9]:
lst = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
import pandas as pd
df = pd.DataFrame(lst, columns =['SNo.', 'Name', 'Age']) 
print(df)

   SNo. Name  Age
0     1  aaa   22
1     2  bbb   25
2     3  ccc   24
