In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix,accuracy_score
ds=pd.read_csv("dataset_website.csv")
ds.head()
ds.info()
ds.isnull()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11055 entries, 0 to 11054
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   index                        11055 non-null  int64
 1   having_IPhaving_IP_Address   11055 non-null  int64
 2   URLURL_Length                11055 non-null  int64
 3   Shortining_Service           11055 non-null  int64
 4   having_At_Symbol             11055 non-null  int64
 5   double_slash_redirecting     11055 non-null  int64
 6   Prefix_Suffix                11055 non-null  int64
 7   having_Sub_Domain            11055 non-null  int64
 8   SSLfinal_State               11055 non-null  int64
 9   Domain_registeration_length  11055 non-null  int64
 10  Favicon                      11055 non-null  int64
 11  port                         11055 non-null  int64
 12  HTTPS_token                  11055 non-null  int64
 13  Request_URL                  11055 non-null  i

index  having_IPhaving_IP_Address  URLURL_Length  Shortining_Service  \
0      False                       False          False               False   
1      False                       False          False               False   
2      False                       False          False               False   
3      False                       False          False               False   
4      False                       False          False               False   
...      ...                         ...            ...                 ...   
11050  False                       False          False               False   
11051  False                       False          False               False   
11052  False                       False          False               False   
11053  False                       False          False               False   
11054  False                       False          False               False   

       having_At_Symbol  double_slash_redirecting  Prefix_Suffix  \
0                 False                     False          False   
1                 False                     False          False   
2                 False                     False          False   
3                 False                     False          False   
4                 False                     False          False   
...                 ...                       ...            ...   
11050             False                     False          False   
11051             False                     False          False   
11052             False                     False          False   
11053             False                     False          False   
11054             False                     False          False   

       having_Sub_Domain  SSLfinal_State  Domain_registeration_length  ...  \
0                  False           False                        False  ...   
1                  False           False                        False  ...   
2                  False           False                        False  ...   
3                  False           False                        False  ...   
4                  False           False                        False  ...   
...                  ...             ...                          ...  ...   
11050              False           False                        False  ...   
11051              False           False                        False  ...   
11052              False           False                        False  ...   
11053              False           False                        False  ...   
11054              False           False                        False  ...   

       popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
0            False   False          False      False        False      False   
1            False   False          False      False        False      False   
2            False   False          False      False        False      False   
3            False   False          False      False        False      False   
4            False   False          False      False        False      False   
...            ...     ...            ...        ...          ...        ...   
11050        False   False          False      False        False      False   
11051        False   False          False      False        False      False   
11052        False   False          False      False        False      False   
11053        False   False          False      False        False      False   
11054        False   False          False      False        False      False   

       Google_Index  Links_pointing_to_page  Statistical_report  Result  
0             False                   False               False   False  
1             False                   False               False   False  
2             False                   False               False   False  
3             False                   False    

In [6]:
x=ds.iloc[:,1:31].values
y=ds.iloc[:,-1].values
print(x,y)
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


[[-1  1  1 ...  1  1 -1]
 [ 1  1  1 ...  1  1  1]
 [ 1  0  1 ...  1  0 -1]
 ...
 [ 1 -1  1 ...  1  0  1]
 [-1 -1  1 ...  1  1  1]
 [-1 -1  1 ... -1  1 -1]] [-1 -1 -1 ... -1 -1 -1]


In [9]:
from sklearn.linear_model import LogisticRegression

lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred1=lr.predict(x_test)
from sklearn.metrics import accuracy_score
log_reg=accuracy_score(y_test,y_pred1)
log_reg

0.9167797376752601

In [16]:
import pickle
pickle.dump(lr,open('Phising_Website.pkl','wb'))